name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.23
  - scipy=1.10
  - matplotlib=3.7
  - h5py=3.8
  - ipykernel=6.25
  - jupyterlab=4.0
  - decorator=4.4
  - pip
