#!/usr/bin/env bash
set -euxo pipefail
# Use the conda env you define in environment.yml (named "ligo")
/srv/conda/envs/ligo/bin/python -m ipykernel install \
  --name ligo \
  --display-name "Python (ligo)" \
  --sys-prefix
